//
//  DigitalphaTests.swift
//  DigitalphaTests
//
//  Created by TJ Usiyan on 2017/07/09.
//  Copyright © 2017 Buttons and Lights LLC. All rights reserved.
//

import XCTest
@testable import Digitalpha

class DigitalphaTests: XCTestCase {
    
    func testCardinalSpelledOutWithDefaultConnector() {
        XCTAssertEqual(0.cardinalStringSpelledOut(), "zero")
        XCTAssertEqual(1.cardinalStringSpelledOut(), "one")
        XCTAssertEqual(2.cardinalStringSpelledOut(), "two")
        XCTAssertEqual(3.cardinalStringSpelledOut(), "three")
        XCTAssertEqual(4.cardinalStringSpelledOut(), "four")
        XCTAssertEqual(5.cardinalStringSpelledOut(), "five")
        XCTAssertEqual(6.cardinalStringSpelledOut(), "six")
        XCTAssertEqual(7.cardinalStringSpelledOut(), "seven")
        XCTAssertEqual(8.cardinalStringSpelledOut(), "eight")
        XCTAssertEqual(9.cardinalStringSpelledOut(), "nine")
        XCTAssertEqual(10.cardinalStringSpelledOut(), "ten")
        XCTAssertEqual(11.cardinalStringSpelledOut(), "eleven")
        XCTAssertEqual(12.cardinalStringSpelledOut(), "twelve")
        XCTAssertEqual(13.cardinalStringSpelledOut(), "thirteen")
        XCTAssertEqual(14.cardinalStringSpelledOut(), "fourteen")
        XCTAssertEqual(15.cardinalStringSpelledOut(), "fifteen")
        XCTAssertEqual(16.cardinalStringSpelledOut(), "sixteen")
        XCTAssertEqual(17.cardinalStringSpelledOut(), "seventeen")
        XCTAssertEqual(18.cardinalStringSpelledOut(), "eighteen")
        XCTAssertEqual(19.cardinalStringSpelledOut(), "nineteen")
        XCTAssertEqual(20.cardinalStringSpelledOut(), "twenty")
        XCTAssertEqual(21.cardinalStringSpelledOut(), "twenty-one")
        XCTAssertEqual(22.cardinalStringSpelledOut(), "twenty-two")
        XCTAssertEqual(23.cardinalStringSpelledOut(), "twenty-three")
        XCTAssertEqual(24.cardinalStringSpelledOut(), "twenty-four")
        XCTAssertEqual(25.cardinalStringSpelledOut(), "twenty-five")
        XCTAssertEqual(26.cardinalStringSpelledOut(), "twenty-six")
        XCTAssertEqual(27.cardinalStringSpelledOut(), "twenty-seven")
        XCTAssertEqual(28.cardinalStringSpelledOut(), "twenty-eight")
        XCTAssertEqual(29.cardinalStringSpelledOut(), "twenty-nine")
        XCTAssertEqual(30.cardinalStringSpelledOut(), "thirty")
        XCTAssertEqual(31.cardinalStringSpelledOut(), "thirty-one")
        XCTAssertEqual(32.cardinalStringSpelledOut(), "thirty-two")
        XCTAssertEqual(40.cardinalStringSpelledOut(), "forty")
        XCTAssertEqual(50.cardinalStringSpelledOut(), "fifty")
        XCTAssertEqual(60.cardinalStringSpelledOut(), "sixty")
        XCTAssertEqual(70.cardinalStringSpelledOut(), "seventy")
        XCTAssertEqual(80.cardinalStringSpelledOut(), "eighty")
        XCTAssertEqual(87.cardinalStringSpelledOut(), "eighty-seven")
        XCTAssertEqual(90.cardinalStringSpelledOut(), "ninety")
        XCTAssertEqual(99.cardinalStringSpelledOut(), "ninety-nine")
        XCTAssertEqual(100.cardinalStringSpelledOut(), "one hundred")
        XCTAssertEqual(101.cardinalStringSpelledOut(), "one hundred one")
        XCTAssertEqual(110.cardinalStringSpelledOut(), "one hundred ten")
        XCTAssertEqual(111.cardinalStringSpelledOut(), "one hundred eleven")
        XCTAssertEqual(120.cardinalStringSpelledOut(), "one hundred twenty")
        XCTAssertEqual(121.cardinalStringSpelledOut(), "one hundred twenty-one")
        XCTAssertEqual(144.cardinalStringSpelledOut(), "one hundred forty-four")
        XCTAssertEqual(200.cardinalStringSpelledOut(), "two hundred")
        XCTAssertEqual(300.cardinalStringSpelledOut(), "three hundred")
        XCTAssertEqual(400.cardinalStringSpelledOut(), "four hundred")
        XCTAssertEqual(500.cardinalStringSpelledOut(), "five hundred")
        XCTAssertEqual(600.cardinalStringSpelledOut(), "six hundred")
        XCTAssertEqual(666.cardinalStringSpelledOut(), "six hundred sixty-six")
        XCTAssertEqual(700.cardinalStringSpelledOut(), "seven hundred")
        XCTAssertEqual(777.cardinalStringSpelledOut(), "seven hundred seventy-seven")
        XCTAssertEqual(800.cardinalStringSpelledOut(), "eight hundred")
        XCTAssertEqual(900.cardinalStringSpelledOut(), "nine hundred")
        XCTAssertEqual(1000.cardinalStringSpelledOut(), "one thousand")
        XCTAssertEqual(1001.cardinalStringSpelledOut(), "one thousand one")
        XCTAssertEqual(1010.cardinalStringSpelledOut(), "one thousand ten")
        XCTAssertEqual(1011.cardinalStringSpelledOut(), "one thousand eleven")
        XCTAssertEqual(1024.cardinalStringSpelledOut(), "one thousand twenty-four")
        XCTAssertEqual(1100.cardinalStringSpelledOut(), "one thousand one hundred")
        XCTAssertEqual(1101.cardinalStringSpelledOut(), "one thousand one hundred one")
        XCTAssertEqual(1728.cardinalStringSpelledOut(), "one thousand seven hundred twenty-eight")
        XCTAssertEqual(2000.cardinalStringSpelledOut(), "two thousand")
        XCTAssertEqual(3000.cardinalStringSpelledOut(), "three thousand")
        XCTAssertEqual(10000.cardinalStringSpelledOut(), "ten thousand")
        XCTAssertEqual(100000.cardinalStringSpelledOut(), "one hundred thousand")
        XCTAssertEqual(500000.cardinalStringSpelledOut(), "five hundred thousand")
        XCTAssertEqual(1000000.cardinalStringSpelledOut(), "one million")
        XCTAssertEqual(1048576.cardinalStringSpelledOut(), "one million forty-eight thousand five hundred seventy-six")
        XCTAssertEqual(10000000.cardinalStringSpelledOut(), "ten million")
        XCTAssertEqual(100000000.cardinalStringSpelledOut(), "one hundred million")
    }

    func testCardinalSpelledOutWithAndConnector() {
        XCTAssertEqual(0.cardinalStringSpelledOut(specialConnector: " and "), "zero")
        XCTAssertEqual(1.cardinalStringSpelledOut(specialConnector: " and "), "one")
        XCTAssertEqual(2.cardinalStringSpelledOut(specialConnector: " and "), "two")
        XCTAssertEqual(3.cardinalStringSpelledOut(specialConnector: " and "), "three")
        XCTAssertEqual(4.cardinalStringSpelledOut(specialConnector: " and "), "four")
        XCTAssertEqual(5.cardinalStringSpelledOut(specialConnector: " and "), "five")
        XCTAssertEqual(6.cardinalStringSpelledOut(specialConnector: " and "), "six")
        XCTAssertEqual(7.cardinalStringSpelledOut(specialConnector: " and "), "seven")
        XCTAssertEqual(8.cardinalStringSpelledOut(specialConnector: " and "), "eight")
        XCTAssertEqual(9.cardinalStringSpelledOut(specialConnector: " and "), "nine")
        XCTAssertEqual(10.cardinalStringSpelledOut(specialConnector: " and "), "ten")
        XCTAssertEqual(11.cardinalStringSpelledOut(specialConnector: " and "), "eleven")
        XCTAssertEqual(12.cardinalStringSpelledOut(specialConnector: " and "), "twelve")
        XCTAssertEqual(13.cardinalStringSpelledOut(specialConnector: " and "), "thirteen")
        XCTAssertEqual(14.cardinalStringSpelledOut(specialConnector: " and "), "fourteen")
        XCTAssertEqual(15.cardinalStringSpelledOut(specialConnector: " and "), "fifteen")
        XCTAssertEqual(16.cardinalStringSpelledOut(specialConnector: " and "), "sixteen")
        XCTAssertEqual(17.cardinalStringSpelledOut(specialConnector: " and "), "seventeen")
        XCTAssertEqual(18.cardinalStringSpelledOut(specialConnector: " and "), "eighteen")
        XCTAssertEqual(19.cardinalStringSpelledOut(specialConnector: " and "), "nineteen")
        XCTAssertEqual(20.cardinalStringSpelledOut(specialConnector: " and "), "twenty")
        XCTAssertEqual(21.cardinalStringSpelledOut(specialConnector: " and "), "twenty-one")
        XCTAssertEqual(22.cardinalStringSpelledOut(specialConnector: " and "), "twenty-two")
        XCTAssertEqual(23.cardinalStringSpelledOut(specialConnector: " and "), "twenty-three")
        XCTAssertEqual(24.cardinalStringSpelledOut(specialConnector: " and "), "twenty-four")
        XCTAssertEqual(25.cardinalStringSpelledOut(specialConnector: " and "), "twenty-five")
        XCTAssertEqual(26.cardinalStringSpelledOut(specialConnector: " and "), "twenty-six")
        XCTAssertEqual(27.cardinalStringSpelledOut(specialConnector: " and "), "twenty-seven")
        XCTAssertEqual(28.cardinalStringSpelledOut(specialConnector: " and "), "twenty-eight")
        XCTAssertEqual(29.cardinalStringSpelledOut(specialConnector: " and "), "twenty-nine")
        XCTAssertEqual(30.cardinalStringSpelledOut(specialConnector: " and "), "thirty")
        XCTAssertEqual(31.cardinalStringSpelledOut(specialConnector: " and "), "thirty-one")
        XCTAssertEqual(32.cardinalStringSpelledOut(specialConnector: " and "), "thirty-two")
        XCTAssertEqual(40.cardinalStringSpelledOut(specialConnector: " and "), "forty")
        XCTAssertEqual(50.cardinalStringSpelledOut(specialConnector: " and "), "fifty")
        XCTAssertEqual(60.cardinalStringSpelledOut(specialConnector: " and "), "sixty")
        XCTAssertEqual(70.cardinalStringSpelledOut(specialConnector: " and "), "seventy")
        XCTAssertEqual(80.cardinalStringSpelledOut(specialConnector: " and "), "eighty")
        XCTAssertEqual(87.cardinalStringSpelledOut(specialConnector: " and "), "eighty-seven")
        XCTAssertEqual(90.cardinalStringSpelledOut(specialConnector: " and "), "ninety")
        XCTAssertEqual(100.cardinalStringSpelledOut(specialConnector: " and "), "one hundred")
        XCTAssertEqual(101.cardinalStringSpelledOut(specialConnector: " and "), "one hundred and one")
        XCTAssertEqual(110.cardinalStringSpelledOut(specialConnector: " and "), "one hundred and ten")
        XCTAssertEqual(111.cardinalStringSpelledOut(specialConnector: " and "), "one hundred and eleven")
        XCTAssertEqual(120.cardinalStringSpelledOut(specialConnector: " and "), "one hundred and twenty")
        XCTAssertEqual(121.cardinalStringSpelledOut(specialConnector: " and "), "one hundred and twenty-one")
        XCTAssertEqual(144.cardinalStringSpelledOut(specialConnector: " and "), "one hundred and forty-four")
        XCTAssertEqual(200.cardinalStringSpelledOut(specialConnector: " and "), "two hundred")
        XCTAssertEqual(300.cardinalStringSpelledOut(specialConnector: " and "), "three hundred")
        XCTAssertEqual(400.cardinalStringSpelledOut(specialConnector: " and "), "four hundred")
        XCTAssertEqual(500.cardinalStringSpelledOut(specialConnector: " and "), "five hundred")
        XCTAssertEqual(600.cardinalStringSpelledOut(specialConnector: " and "), "six hundred")
        XCTAssertEqual(666.cardinalStringSpelledOut(specialConnector: " and "), "six hundred and sixty-six")
        XCTAssertEqual(700.cardinalStringSpelledOut(specialConnector: " and "), "seven hundred")
        XCTAssertEqual(777.cardinalStringSpelledOut(specialConnector: " and "), "seven hundred and seventy-seven")
        XCTAssertEqual(800.cardinalStringSpelledOut(specialConnector: " and "), "eight hundred")
        XCTAssertEqual(900.cardinalStringSpelledOut(specialConnector: " and "), "nine hundred")
        XCTAssertEqual(1000.cardinalStringSpelledOut(specialConnector: " and "), "one thousand")
        XCTAssertEqual(1001.cardinalStringSpelledOut(specialConnector: " and "), "one thousand and one")
        XCTAssertEqual(1010.cardinalStringSpelledOut(specialConnector: " and "), "one thousand and ten")
        XCTAssertEqual(1011.cardinalStringSpelledOut(specialConnector: " and "), "one thousand and eleven")
        XCTAssertEqual(1024.cardinalStringSpelledOut(specialConnector: " and "), "one thousand and twenty-four")
        XCTAssertEqual(1100.cardinalStringSpelledOut(specialConnector: " and "), "one thousand one hundred")
        XCTAssertEqual(1101.cardinalStringSpelledOut(specialConnector: " and "), "one thousand one hundred and one")
        XCTAssertEqual(1728.cardinalStringSpelledOut(specialConnector: " and "), "one thousand seven hundred and twenty-eight")
        XCTAssertEqual(2000.cardinalStringSpelledOut(specialConnector: " and "), "two thousand")
        XCTAssertEqual(3000.cardinalStringSpelledOut(specialConnector: " and "), "three thousand")
        XCTAssertEqual(10000.cardinalStringSpelledOut(specialConnector: " and "), "ten thousand")
        XCTAssertEqual(100000.cardinalStringSpelledOut(specialConnector: " and "), "one hundred thousand")
        XCTAssertEqual(500000.cardinalStringSpelledOut(specialConnector: " and "), "five hundred thousand")
        XCTAssertEqual(1000000.cardinalStringSpelledOut(specialConnector: " and "), "one million")
        XCTAssertEqual(1048576.cardinalStringSpelledOut(specialConnector: " and "), "one million forty-eight thousand five hundred and seventy-six")
        XCTAssertEqual(10000000.cardinalStringSpelledOut(specialConnector: " and "), "ten million")
        XCTAssertEqual(100000000.cardinalStringSpelledOut(specialConnector: " and "), "one hundred million")
    }

    func testOrdinalSpelledOutWithDefaultConnector() {
        XCTAssertEqual(0.ordinalStringSpelledOut(), "zeroth")
        XCTAssertEqual(1.ordinalStringSpelledOut(), "first")
        XCTAssertEqual(2.ordinalStringSpelledOut(), "second")
        XCTAssertEqual(3.ordinalStringSpelledOut(), "third")
        XCTAssertEqual(4.ordinalStringSpelledOut(), "fourth")
        XCTAssertEqual(5.ordinalStringSpelledOut(), "fifth")
        XCTAssertEqual(6.ordinalStringSpelledOut(), "sixth")
        XCTAssertEqual(7.ordinalStringSpelledOut(), "seventh")
        XCTAssertEqual(8.ordinalStringSpelledOut(), "eighth")
        XCTAssertEqual(9.ordinalStringSpelledOut(), "ninth")
        XCTAssertEqual(10.ordinalStringSpelledOut(), "tenth")
        XCTAssertEqual(11.ordinalStringSpelledOut(), "eleventh")
        XCTAssertEqual(12.ordinalStringSpelledOut(), "twelfth")
        XCTAssertEqual(13.ordinalStringSpelledOut(), "thirteenth")
        XCTAssertEqual(14.ordinalStringSpelledOut(), "fourteenth")
        XCTAssertEqual(15.ordinalStringSpelledOut(), "fifteenth")
        XCTAssertEqual(16.ordinalStringSpelledOut(), "sixteenth")
        XCTAssertEqual(17.ordinalStringSpelledOut(), "seventeenth")
        XCTAssertEqual(18.ordinalStringSpelledOut(), "eighteenth")
        XCTAssertEqual(19.ordinalStringSpelledOut(), "nineteenth")
        XCTAssertEqual(20.ordinalStringSpelledOut(), "twentieth")
        XCTAssertEqual(21.ordinalStringSpelledOut(), "twenty-first")
        XCTAssertEqual(22.ordinalStringSpelledOut(), "twenty-second")
        XCTAssertEqual(23.ordinalStringSpelledOut(), "twenty-third")
        XCTAssertEqual(24.ordinalStringSpelledOut(), "twenty-fourth")
        XCTAssertEqual(25.ordinalStringSpelledOut(), "twenty-fifth")
        XCTAssertEqual(26.ordinalStringSpelledOut(), "twenty-sixth")
        XCTAssertEqual(27.ordinalStringSpelledOut(), "twenty-seventh")
        XCTAssertEqual(28.ordinalStringSpelledOut(), "twenty-eighth")
        XCTAssertEqual(29.ordinalStringSpelledOut(), "twenty-ninth")
        XCTAssertEqual(30.ordinalStringSpelledOut(), "thirtieth")
        XCTAssertEqual(31.ordinalStringSpelledOut(), "thirty-first")
        XCTAssertEqual(32.ordinalStringSpelledOut(), "thirty-second")
        XCTAssertEqual(40.ordinalStringSpelledOut(), "fortieth")
        XCTAssertEqual(50.ordinalStringSpelledOut(), "fiftieth")
        XCTAssertEqual(60.ordinalStringSpelledOut(), "sixtieth")
        XCTAssertEqual(70.ordinalStringSpelledOut(), "seventieth")
        XCTAssertEqual(80.ordinalStringSpelledOut(), "eightieth")
        XCTAssertEqual(87.ordinalStringSpelledOut(), "eighty-seventh")
        XCTAssertEqual(90.ordinalStringSpelledOut(), "ninetieth")
        XCTAssertEqual(99.ordinalStringSpelledOut(), "ninety-ninth")
        XCTAssertEqual(100.ordinalStringSpelledOut(), "one hundredth")
        XCTAssertEqual(101.ordinalStringSpelledOut(), "one hundred first")
        XCTAssertEqual(110.ordinalStringSpelledOut(), "one hundred tenth")
        XCTAssertEqual(111.ordinalStringSpelledOut(), "one hundred eleventh")
        XCTAssertEqual(120.ordinalStringSpelledOut(), "one hundred twentieth")
        XCTAssertEqual(121.ordinalStringSpelledOut(), "one hundred twenty-first")
        XCTAssertEqual(144.ordinalStringSpelledOut(), "one hundred forty-fourth")
        XCTAssertEqual(200.ordinalStringSpelledOut(), "two hundredth")
        XCTAssertEqual(300.ordinalStringSpelledOut(), "three hundredth")
        XCTAssertEqual(400.ordinalStringSpelledOut(), "four hundredth")
        XCTAssertEqual(500.ordinalStringSpelledOut(), "five hundredth")
        XCTAssertEqual(600.ordinalStringSpelledOut(), "six hundredth")
        XCTAssertEqual(666.ordinalStringSpelledOut(), "six hundred sixty-sixth")
        XCTAssertEqual(700.ordinalStringSpelledOut(), "seven hundredth")
        XCTAssertEqual(777.ordinalStringSpelledOut(), "seven hundred seventy-seventh")
        XCTAssertEqual(800.ordinalStringSpelledOut(), "eight hundredth")
        XCTAssertEqual(900.ordinalStringSpelledOut(), "nine hundredth")
        XCTAssertEqual(1000.ordinalStringSpelledOut(), "one thousandth")
        XCTAssertEqual(1001.ordinalStringSpelledOut(), "one thousand first")
        XCTAssertEqual(1010.ordinalStringSpelledOut(), "one thousand tenth")
        XCTAssertEqual(1011.ordinalStringSpelledOut(), "one thousand eleventh")
        XCTAssertEqual(1024.ordinalStringSpelledOut(), "one thousand twenty-fourth")
        XCTAssertEqual(1100.ordinalStringSpelledOut(), "one thousand one hundredth")
        XCTAssertEqual(1101.ordinalStringSpelledOut(), "one thousand one hundred first")
        XCTAssertEqual(1728.ordinalStringSpelledOut(), "one thousand seven hundred twenty-eighth")
        XCTAssertEqual(2000.ordinalStringSpelledOut(), "two thousandth")
        XCTAssertEqual(3000.ordinalStringSpelledOut(), "three thousandth")
        XCTAssertEqual(10000.ordinalStringSpelledOut(), "ten thousandth")
        XCTAssertEqual(100000.ordinalStringSpelledOut(), "one hundred thousandth")
        XCTAssertEqual(500000.ordinalStringSpelledOut(), "five hundred thousandth")
        XCTAssertEqual(1000000.ordinalStringSpelledOut(), "one millionth")
        XCTAssertEqual(1048576.ordinalStringSpelledOut(), "one million forty-eight thousand five hundred seventy-sixth")
        XCTAssertEqual(10000000.ordinalStringSpelledOut(), "ten millionth")
        XCTAssertEqual(100000000.ordinalStringSpelledOut(), "one hundred millionth")
    }

    func testNegativeCardinalSpelledOutWithDefaultConnector() {
        XCTAssertEqual((-0).cardinalStringSpelledOut(), "zero")
        XCTAssertEqual((-1).cardinalStringSpelledOut(), "negative one")
        XCTAssertEqual((-2).cardinalStringSpelledOut(), "negative two")
        XCTAssertEqual((-3).cardinalStringSpelledOut(), "negative three")
        XCTAssertEqual((-4).cardinalStringSpelledOut(), "negative four")
        XCTAssertEqual((-5).cardinalStringSpelledOut(), "negative five")
        XCTAssertEqual((-6).cardinalStringSpelledOut(), "negative six")
        XCTAssertEqual((-7).cardinalStringSpelledOut(), "negative seven")
        XCTAssertEqual((-8).cardinalStringSpelledOut(), "negative eight")
        XCTAssertEqual((-9).cardinalStringSpelledOut(), "negative nine")
        XCTAssertEqual((-10).cardinalStringSpelledOut(), "negative ten")
        XCTAssertEqual((-11).cardinalStringSpelledOut(), "negative eleven")
        XCTAssertEqual((-12).cardinalStringSpelledOut(), "negative twelve")
        XCTAssertEqual((-13).cardinalStringSpelledOut(), "negative thirteen")
        XCTAssertEqual((-14).cardinalStringSpelledOut(), "negative fourteen")
        XCTAssertEqual((-15).cardinalStringSpelledOut(), "negative fifteen")
        XCTAssertEqual((-16).cardinalStringSpelledOut(), "negative sixteen")
        XCTAssertEqual((-17).cardinalStringSpelledOut(), "negative seventeen")
        XCTAssertEqual((-18).cardinalStringSpelledOut(), "negative eighteen")
        XCTAssertEqual((-19).cardinalStringSpelledOut(), "negative nineteen")
        XCTAssertEqual((-20).cardinalStringSpelledOut(), "negative twenty")
        XCTAssertEqual((-21).cardinalStringSpelledOut(), "negative twenty-one")
        XCTAssertEqual((-22).cardinalStringSpelledOut(), "negative twenty-two")
        XCTAssertEqual((-23).cardinalStringSpelledOut(), "negative twenty-three")
        XCTAssertEqual((-24).cardinalStringSpelledOut(), "negative twenty-four")
        XCTAssertEqual((-25).cardinalStringSpelledOut(), "negative twenty-five")
        XCTAssertEqual((-26).cardinalStringSpelledOut(), "negative twenty-six")
        XCTAssertEqual((-27).cardinalStringSpelledOut(), "negative twenty-seven")
        XCTAssertEqual((-28).cardinalStringSpelledOut(), "negative twenty-eight")
        XCTAssertEqual((-29).cardinalStringSpelledOut(), "negative twenty-nine")
        XCTAssertEqual((-30).cardinalStringSpelledOut(), "negative thirty")
        XCTAssertEqual((-31).cardinalStringSpelledOut(), "negative thirty-one")
        XCTAssertEqual((-32).cardinalStringSpelledOut(), "negative thirty-two")
        XCTAssertEqual((-40).cardinalStringSpelledOut(), "negative forty")
        XCTAssertEqual((-50).cardinalStringSpelledOut(), "negative fifty")
        XCTAssertEqual((-60).cardinalStringSpelledOut(), "negative sixty")
        XCTAssertEqual((-70).cardinalStringSpelledOut(), "negative seventy")
        XCTAssertEqual((-80).cardinalStringSpelledOut(), "negative eighty")
        XCTAssertEqual((-87).cardinalStringSpelledOut(), "negative eighty-seven")
        XCTAssertEqual((-90).cardinalStringSpelledOut(), "negative ninety")
        XCTAssertEqual((-99).cardinalStringSpelledOut(), "negative ninety-nine")
        XCTAssertEqual((-100).cardinalStringSpelledOut(), "negative one hundred")
        XCTAssertEqual((-101).cardinalStringSpelledOut(), "negative one hundred one")
        XCTAssertEqual((-110).cardinalStringSpelledOut(), "negative one hundred ten")
        XCTAssertEqual((-111).cardinalStringSpelledOut(), "negative one hundred eleven")
        XCTAssertEqual((-120).cardinalStringSpelledOut(), "negative one hundred twenty")
        XCTAssertEqual((-121).cardinalStringSpelledOut(), "negative one hundred twenty-one")
        XCTAssertEqual((-144).cardinalStringSpelledOut(), "negative one hundred forty-four")
        XCTAssertEqual((-200).cardinalStringSpelledOut(), "negative two hundred")
        XCTAssertEqual((-300).cardinalStringSpelledOut(), "negative three hundred")
        XCTAssertEqual((-400).cardinalStringSpelledOut(), "negative four hundred")
        XCTAssertEqual((-500).cardinalStringSpelledOut(), "negative five hundred")
        XCTAssertEqual((-600).cardinalStringSpelledOut(), "negative six hundred")
        XCTAssertEqual((-666).cardinalStringSpelledOut(), "negative six hundred sixty-six")
        XCTAssertEqual((-700).cardinalStringSpelledOut(), "negative seven hundred")
        XCTAssertEqual((-777).cardinalStringSpelledOut(), "negative seven hundred seventy-seven")
        XCTAssertEqual((-800).cardinalStringSpelledOut(), "negative eight hundred")
        XCTAssertEqual((-900).cardinalStringSpelledOut(), "negative nine hundred")
        XCTAssertEqual((-1000).cardinalStringSpelledOut(), "negative one thousand")
        XCTAssertEqual((-1001).cardinalStringSpelledOut(), "negative one thousand one")
        XCTAssertEqual((-1010).cardinalStringSpelledOut(), "negative one thousand ten")
        XCTAssertEqual((-1011).cardinalStringSpelledOut(), "negative one thousand eleven")
        XCTAssertEqual((-1024).cardinalStringSpelledOut(), "negative one thousand twenty-four")
        XCTAssertEqual((-1100).cardinalStringSpelledOut(), "negative one thousand one hundred")
        XCTAssertEqual((-1101).cardinalStringSpelledOut(), "negative one thousand one hundred one")
        XCTAssertEqual((-1728).cardinalStringSpelledOut(), "negative one thousand seven hundred twenty-eight")
        XCTAssertEqual((-2000).cardinalStringSpelledOut(), "negative two thousand")
        XCTAssertEqual((-3000).cardinalStringSpelledOut(), "negative three thousand")
        XCTAssertEqual((-10000).cardinalStringSpelledOut(), "negative ten thousand")
        XCTAssertEqual((-100000).cardinalStringSpelledOut(), "negative one hundred thousand")
        XCTAssertEqual((-500000).cardinalStringSpelledOut(), "negative five hundred thousand")
        XCTAssertEqual((-1000000).cardinalStringSpelledOut(), "negative one million")
        XCTAssertEqual((-1048576).cardinalStringSpelledOut(), "negative one million forty-eight thousand five hundred seventy-six")
        XCTAssertEqual((-10000000).cardinalStringSpelledOut(), "negative ten million")
        XCTAssertEqual((-100000000).cardinalStringSpelledOut(), "negative one hundred million")
    }

    func testNegativeCardinalSpelledOutWithAndConnector() {
        XCTAssertEqual((-0).cardinalStringSpelledOut(specialConnector: " and "), "zero")
        XCTAssertEqual((-1).cardinalStringSpelledOut(specialConnector: " and "), "negative one")
        XCTAssertEqual((-2).cardinalStringSpelledOut(specialConnector: " and "), "negative two")
        XCTAssertEqual((-3).cardinalStringSpelledOut(specialConnector: " and "), "negative three")
        XCTAssertEqual((-4).cardinalStringSpelledOut(specialConnector: " and "), "negative four")
        XCTAssertEqual((-5).cardinalStringSpelledOut(specialConnector: " and "), "negative five")
        XCTAssertEqual((-6).cardinalStringSpelledOut(specialConnector: " and "), "negative six")
        XCTAssertEqual((-7).cardinalStringSpelledOut(specialConnector: " and "), "negative seven")
        XCTAssertEqual((-8).cardinalStringSpelledOut(specialConnector: " and "), "negative eight")
        XCTAssertEqual((-9).cardinalStringSpelledOut(specialConnector: " and "), "negative nine")
        XCTAssertEqual((-10).cardinalStringSpelledOut(specialConnector: " and "), "negative ten")
        XCTAssertEqual((-11).cardinalStringSpelledOut(specialConnector: " and "), "negative eleven")
        XCTAssertEqual((-12).cardinalStringSpelledOut(specialConnector: " and "), "negative twelve")
        XCTAssertEqual((-13).cardinalStringSpelledOut(specialConnector: " and "), "negative thirteen")
        XCTAssertEqual((-14).cardinalStringSpelledOut(specialConnector: " and "), "negative fourteen")
        XCTAssertEqual((-15).cardinalStringSpelledOut(specialConnector: " and "), "negative fifteen")
        XCTAssertEqual((-16).cardinalStringSpelledOut(specialConnector: " and "), "negative sixteen")
        XCTAssertEqual((-17).cardinalStringSpelledOut(specialConnector: " and "), "negative seventeen")
        XCTAssertEqual((-18).cardinalStringSpelledOut(specialConnector: " and "), "negative eighteen")
        XCTAssertEqual((-19).cardinalStringSpelledOut(specialConnector: " and "), "negative nineteen")
        XCTAssertEqual((-20).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty")
        XCTAssertEqual((-21).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-one")
        XCTAssertEqual((-22).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-two")
        XCTAssertEqual((-23).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-three")
        XCTAssertEqual((-24).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-four")
        XCTAssertEqual((-25).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-five")
        XCTAssertEqual((-26).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-six")
        XCTAssertEqual((-27).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-seven")
        XCTAssertEqual((-28).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-eight")
        XCTAssertEqual((-29).cardinalStringSpelledOut(specialConnector: " and "), "negative twenty-nine")
        XCTAssertEqual((-30).cardinalStringSpelledOut(specialConnector: " and "), "negative thirty")
        XCTAssertEqual((-31).cardinalStringSpelledOut(specialConnector: " and "), "negative thirty-one")
        XCTAssertEqual((-32).cardinalStringSpelledOut(specialConnector: " and "), "negative thirty-two")
        XCTAssertEqual((-40).cardinalStringSpelledOut(specialConnector: " and "), "negative forty")
        XCTAssertEqual((-50).cardinalStringSpelledOut(specialConnector: " and "), "negative fifty")
        XCTAssertEqual((-60).cardinalStringSpelledOut(specialConnector: " and "), "negative sixty")
        XCTAssertEqual((-70).cardinalStringSpelledOut(specialConnector: " and "), "negative seventy")
        XCTAssertEqual((-80).cardinalStringSpelledOut(specialConnector: " and "), "negative eighty")
        XCTAssertEqual((-87).cardinalStringSpelledOut(specialConnector: " and "), "negative eighty-seven")
        XCTAssertEqual((-90).cardinalStringSpelledOut(specialConnector: " and "), "negative ninety")
        XCTAssertEqual((-100).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred")
        XCTAssertEqual((-101).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred and one")
        XCTAssertEqual((-110).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred and ten")
        XCTAssertEqual((-111).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred and eleven")
        XCTAssertEqual((-120).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred and twenty")
        XCTAssertEqual((-121).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred and twenty-one")
        XCTAssertEqual((-144).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred and forty-four")
        XCTAssertEqual((-200).cardinalStringSpelledOut(specialConnector: " and "), "negative two hundred")
        XCTAssertEqual((-300).cardinalStringSpelledOut(specialConnector: " and "), "negative three hundred")
        XCTAssertEqual((-400).cardinalStringSpelledOut(specialConnector: " and "), "negative four hundred")
        XCTAssertEqual((-500).cardinalStringSpelledOut(specialConnector: " and "), "negative five hundred")
        XCTAssertEqual((-600).cardinalStringSpelledOut(specialConnector: " and "), "negative six hundred")
        XCTAssertEqual((-666).cardinalStringSpelledOut(specialConnector: " and "), "negative six hundred and sixty-six")
        XCTAssertEqual((-700).cardinalStringSpelledOut(specialConnector: " and "), "negative seven hundred")
        XCTAssertEqual((-777).cardinalStringSpelledOut(specialConnector: " and "), "negative seven hundred and seventy-seven")
        XCTAssertEqual((-800).cardinalStringSpelledOut(specialConnector: " and "), "negative eight hundred")
        XCTAssertEqual((-900).cardinalStringSpelledOut(specialConnector: " and "), "negative nine hundred")
        XCTAssertEqual((-1000).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand")
        XCTAssertEqual((-1001).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand and one")
        XCTAssertEqual((-1010).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand and ten")
        XCTAssertEqual((-1011).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand and eleven")
        XCTAssertEqual((-1024).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand and twenty-four")
        XCTAssertEqual((-1100).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand one hundred")
        XCTAssertEqual((-1101).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand one hundred and one")
        XCTAssertEqual((-1728).cardinalStringSpelledOut(specialConnector: " and "), "negative one thousand seven hundred and twenty-eight")
        XCTAssertEqual((-2000).cardinalStringSpelledOut(specialConnector: " and "), "negative two thousand")
        XCTAssertEqual((-3000).cardinalStringSpelledOut(specialConnector: " and "), "negative three thousand")
        XCTAssertEqual((-10000).cardinalStringSpelledOut(specialConnector: " and "), "negative ten thousand")
        XCTAssertEqual((-100000).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred thousand")
        XCTAssertEqual((-500000).cardinalStringSpelledOut(specialConnector: " and "), "negative five hundred thousand")
        XCTAssertEqual((-1000000).cardinalStringSpelledOut(specialConnector: " and "), "negative one million")
        XCTAssertEqual((-1048576).cardinalStringSpelledOut(specialConnector: " and "), "negative one million forty-eight thousand five hundred and seventy-six")
        XCTAssertEqual((-10000000).cardinalStringSpelledOut(specialConnector: " and "), "negative ten million")
        XCTAssertEqual((-100000000).cardinalStringSpelledOut(specialConnector: " and "), "negative one hundred million")
    }

    func testNegativeOrdinalSpelledOutWithDefaultConnector() {
        XCTAssertEqual((-0).ordinalStringSpelledOut(), "zeroth")
        XCTAssertEqual((-1).ordinalStringSpelledOut(), "negative first")
        XCTAssertEqual((-2).ordinalStringSpelledOut(), "negative second")
        XCTAssertEqual((-3).ordinalStringSpelledOut(), "negative third")
        XCTAssertEqual((-4).ordinalStringSpelledOut(), "negative fourth")
        XCTAssertEqual((-5).ordinalStringSpelledOut(), "negative fifth")
        XCTAssertEqual((-6).ordinalStringSpelledOut(), "negative sixth")
        XCTAssertEqual((-7).ordinalStringSpelledOut(), "negative seventh")
        XCTAssertEqual((-8).ordinalStringSpelledOut(), "negative eighth")
        XCTAssertEqual((-9).ordinalStringSpelledOut(), "negative ninth")
        XCTAssertEqual((-10).ordinalStringSpelledOut(), "negative tenth")
        XCTAssertEqual((-11).ordinalStringSpelledOut(), "negative eleventh")
        XCTAssertEqual((-12).ordinalStringSpelledOut(), "negative twelfth")
        XCTAssertEqual((-13).ordinalStringSpelledOut(), "negative thirteenth")
        XCTAssertEqual((-14).ordinalStringSpelledOut(), "negative fourteenth")
        XCTAssertEqual((-15).ordinalStringSpelledOut(), "negative fifteenth")
        XCTAssertEqual((-16).ordinalStringSpelledOut(), "negative sixteenth")
        XCTAssertEqual((-17).ordinalStringSpelledOut(), "negative seventeenth")
        XCTAssertEqual((-18).ordinalStringSpelledOut(), "negative eighteenth")
        XCTAssertEqual((-19).ordinalStringSpelledOut(), "negative nineteenth")
        XCTAssertEqual((-20).ordinalStringSpelledOut(), "negative twentieth")
        XCTAssertEqual((-21).ordinalStringSpelledOut(), "negative twenty-first")
        XCTAssertEqual((-22).ordinalStringSpelledOut(), "negative twenty-second")
        XCTAssertEqual((-23).ordinalStringSpelledOut(), "negative twenty-third")
        XCTAssertEqual((-24).ordinalStringSpelledOut(), "negative twenty-fourth")
        XCTAssertEqual((-25).ordinalStringSpelledOut(), "negative twenty-fifth")
        XCTAssertEqual((-26).ordinalStringSpelledOut(), "negative twenty-sixth")
        XCTAssertEqual((-27).ordinalStringSpelledOut(), "negative twenty-seventh")
        XCTAssertEqual((-28).ordinalStringSpelledOut(), "negative twenty-eighth")
        XCTAssertEqual((-29).ordinalStringSpelledOut(), "negative twenty-ninth")
        XCTAssertEqual((-30).ordinalStringSpelledOut(), "negative thirtieth")
        XCTAssertEqual((-31).ordinalStringSpelledOut(), "negative thirty-first")
        XCTAssertEqual((-32).ordinalStringSpelledOut(), "negative thirty-second")
        XCTAssertEqual((-40).ordinalStringSpelledOut(), "negative fortieth")
        XCTAssertEqual((-50).ordinalStringSpelledOut(), "negative fiftieth")
        XCTAssertEqual((-60).ordinalStringSpelledOut(), "negative sixtieth")
        XCTAssertEqual((-70).ordinalStringSpelledOut(), "negative seventieth")
        XCTAssertEqual((-80).ordinalStringSpelledOut(), "negative eightieth")
        XCTAssertEqual((-87).ordinalStringSpelledOut(), "negative eighty-seventh")
        XCTAssertEqual((-90).ordinalStringSpelledOut(), "negative ninetieth")
        XCTAssertEqual((-99).ordinalStringSpelledOut(), "negative ninety-ninth")
        XCTAssertEqual((-100).ordinalStringSpelledOut(), "negative one hundredth")
        XCTAssertEqual((-101).ordinalStringSpelledOut(), "negative one hundred first")
        XCTAssertEqual((-110).ordinalStringSpelledOut(), "negative one hundred tenth")
        XCTAssertEqual((-111).ordinalStringSpelledOut(), "negative one hundred eleventh")
        XCTAssertEqual((-120).ordinalStringSpelledOut(), "negative one hundred twentieth")
        XCTAssertEqual((-121).ordinalStringSpelledOut(), "negative one hundred twenty-first")
        XCTAssertEqual((-144).ordinalStringSpelledOut(), "negative one hundred forty-fourth")
        XCTAssertEqual((-200).ordinalStringSpelledOut(), "negative two hundredth")
        XCTAssertEqual((-300).ordinalStringSpelledOut(), "negative three hundredth")
        XCTAssertEqual((-400).ordinalStringSpelledOut(), "negative four hundredth")
        XCTAssertEqual((-500).ordinalStringSpelledOut(), "negative five hundredth")
        XCTAssertEqual((-600).ordinalStringSpelledOut(), "negative six hundredth")
        XCTAssertEqual((-666).ordinalStringSpelledOut(), "negative six hundred sixty-sixth")
        XCTAssertEqual((-700).ordinalStringSpelledOut(), "negative seven hundredth")
        XCTAssertEqual((-777).ordinalStringSpelledOut(), "negative seven hundred seventy-seventh")
        XCTAssertEqual((-800).ordinalStringSpelledOut(), "negative eight hundredth")
        XCTAssertEqual((-900).ordinalStringSpelledOut(), "negative nine hundredth")
        XCTAssertEqual((-1000).ordinalStringSpelledOut(), "negative one thousandth")
        XCTAssertEqual((-1001).ordinalStringSpelledOut(), "negative one thousand first")
        XCTAssertEqual((-1010).ordinalStringSpelledOut(), "negative one thousand tenth")
        XCTAssertEqual((-1011).ordinalStringSpelledOut(), "negative one thousand eleventh")
        XCTAssertEqual((-1024).ordinalStringSpelledOut(), "negative one thousand twenty-fourth")
        XCTAssertEqual((-1100).ordinalStringSpelledOut(), "negative one thousand one hundredth")
        XCTAssertEqual((-1101).ordinalStringSpelledOut(), "negative one thousand one hundred first")
        XCTAssertEqual((-1728).ordinalStringSpelledOut(), "negative one thousand seven hundred twenty-eighth")
        XCTAssertEqual((-2000).ordinalStringSpelledOut(), "negative two thousandth")
        XCTAssertEqual((-3000).ordinalStringSpelledOut(), "negative three thousandth")
        XCTAssertEqual((-10000).ordinalStringSpelledOut(), "negative ten thousandth")
        XCTAssertEqual((-100000).ordinalStringSpelledOut(), "negative one hundred thousandth")
        XCTAssertEqual((-500000).ordinalStringSpelledOut(), "negative five hundred thousandth")
        XCTAssertEqual((-1000000).ordinalStringSpelledOut(), "negative one millionth")
        XCTAssertEqual((-1048576).ordinalStringSpelledOut(), "negative one million forty-eight thousand five hundred seventy-sixth")
        XCTAssertEqual((-10000000).ordinalStringSpelledOut(), "negative ten millionth")
        XCTAssertEqual((-100000000).ordinalStringSpelledOut(), "negative one hundred millionth")
    }

}
